[workspace]
authors = ["Yaoxiang Li <liyaoxiang@outlook.com>"]
channels = ["conda-forge", "bioconda", "nodefaults", "https://conda.anaconda.org/bioconda"]
name = "dap_seq_fastqc"
platforms = ["linux-64", "osx-64", "osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
fastqc = { version = "0.12.1.*", channel = "bioconda" }
